### ISSUE TITLE
Could you add guide

### ISSUE THREAD

**Issue by rusmichal** [modernistik/parse-file-migration#1]
Hello 

I've deployed your tool on heroku server because I want transfer my parse file to AWS. To be honest I am not sure what is going on. I've stared migration process. I looked at Sidekiq dashborad and see couple of values.

 I have lot of Failed jobs I guess it is bad. But Why? Can I check logs or something like that?

Is it possible to stop process?
![zrzut ekranu 2016-12-22 o 15 01 11](https://cloud.githubusercontent.com/assets/15652344/21428014/2865cfd0-c858-11e6-99da-0a539d0c9e8b.png)

**Comment by apersaud** [comment]
A few things could have happened:
* Make sure you are pointing to the proper Parse Server URL. I recommend using `https://api.parse.com/1/` to get the proper file URL. The file URL is dependent on the server configuration which requires the proper `fileKey` parameter.
* Make sure the AWS credentials have the proper read/write privileges to the S3 bucket you created. See [Policy Document Configuration](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters).
* I would then see if any files got copied over so your S3 bucket. If some did successfully copy over, there might be an issue with some files stored in Parse. You can verify which files failed by logging into the REDIS instance you are using and doing a [SDIFF](https://redis.io/commands/sdiff) between `parse:files` and `s3:files` keys. This will give you the files that were not successfully copied over.
* If not files were copied over to the bucket, there must be something wrong with authentication. If you are running on Heroku you can check the logs `heroku logs -n 1000 -a NAME_OF_YOUR_APP` and paste that below if possible.

**Comment by rusmichal** [comment]
Hello Thx for your comment.

First I check my logs I this is what I got.

```
4 TID-ov5tgnvds Worker::S3FileMigrator JID-a807f6e91796094c1a751e21 DEBUG: Retries exhausted for job
2017-01-03T12:33:08.061628+00:00 app[worker.1]: 4 TID-ov5tgnvds Worker::S3FileMigrator JID-a807f6e91796094c1a751e21 INFO: Adding dead Worker::S3FileMigrator job a807f6e91796094c1a751e21
2017-01-03T12:33:08.073780+00:00 app[worker.1]: 4 TID-ov5tgnvds Worker::S3FileMigrator JID-a807f6e91796094c1a751e21 INFO: fail: 0.793 sec
2017-01-03T12:33:08.073964+00:00 app[worker.1]: 4 TID-ov5tgnvds WARN: {"context":"Job raised exception","job":{"class":"Worker::S3FileMigrator","args":["http://files.parsetfss.com/97876fc6-b402-416c-9531-80c903b7b63a/tfss-a4e35a9c-a8f2-44d6-ad5c-3249865562a9-Thumbnail.jpg",{"className":"Photo","objectId":"ANV8qLWFsP"}],"retry":4,"queue":"default","jid":"a807f6e91796094c1a751e21","created_at":1482414598.4311204,"enqueued_at":1483446787.278326,"error_message":"","error_class":"Aws::S3::Errors::BadRequest","failed_at":1482415526.5514896,"retry_count":4,"retried_at":1483446788.0614874},"jobstr":"{\"class\":\"Worker::S3FileMigrator\",\"args\":[\"http://files.parsetfss.com/97876fc6-b402-416c-9531-80c903b7b63a/tfss-a4e35a9c-a8f2-44d6-ad5c-3249865562a9-Thumbnail.jpg\",{\"className\":\"Photo\",\"objectId\":\"ANV8qLWFsP\"}],\"retry\":4,\"queue\":\"default\",\"jid\":\"a807f6e91796094c1a751e21\",\"created_at\":1482414598.4311204,\"enqueued_at\":1483446787.278326,\"error_message\":\"\",\"error_class\":\"Aws::S3::Errors::BadRequest\",\"failed_at\":1482415526.5514896,\"retry_count\":3,\"retried_at\":1482483687.2547894}"}
2017-01-03T12:33:08.073984+00:00 app[worker.1]: 4 TID-ov5tgnvds WARN: Aws::S3::Errors::BadRequest:
2017-01-03T12:33:08.074035+00:00 app[worker.1]: 4 TID-ov5tgnvds WARN: /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.6.19/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?'
2017-01-03T12:33:08.074037+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.6.19/lib/aws-sdk-resources/resource.rb:131:in `exists?'
2017-01-03T12:33:08.074038+00:00 app[worker.1]: /app/config/migration.rb:221:in `perform'
2017-01-03T12:33:08.074039+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:158:in `execute_job'
2017-01-03T12:33:08.074040+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
2017-01-03T12:33:08.074040+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
2017-01-03T12:33:08.074041+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
2017-01-03T12:33:08.074042+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
2017-01-03T12:33:08.074043+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
2017-01-03T12:33:08.074043+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-03T12:33:08.074044+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
2017-01-03T12:33:08.074045+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/logging.rb:32:in `with_context'
2017-01-03T12:33:08.074046+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/server/logging.rb:7:in `call'
2017-01-03T12:33:08.074046+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
2017-01-03T12:33:08.074047+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2017-01-03T12:33:08.074048+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:174:in `stats'
2017-01-03T12:33:08.074048+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
2017-01-03T12:33:08.074049+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:131:in `block in process'
2017-01-03T12:33:08.074050+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
2017-01-03T12:33:08.074050+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:126:in `process'
2017-01-03T12:33:08.074051+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:82:in `process_one'
2017-01-03T12:33:08.074052+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/processor.rb:70:in `run'
2017-01-03T12:33:08.074052+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:17:in `watchdog'
2017-01-03T12:33:08.074053+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.7/lib/sidekiq/util.rb:25:in `block in safe_thread'
2017-01-03T12:33:17.818565+00:00 heroku[router]: at=info method=GET path="/busy" host=parse-file-migration-tool.herokuapp.com request_id=eeceaa90-181d-4db4-bc3d-450f0756e4f5 fwd="109.173.159.0" dyno=web.1 connect=1ms service=29ms status=200 bytes=8071
2017-01-03T12:33:24.167212+00:00 app[worker.1]: [ParseQuery] Skips larger than 10000 are not allowed
2017-01-03T12:33:24.170147+00:00 app[worker.1]: 4 TID-ov5t9qeck Worker::RecordSetProcessor JID-9f95e400eca94d2fdb549c54 INFO: start
2017-01-03T12:33:24.173597+00:00 app[worker.1]: 4 TID-ov5t9qdik Worker::RecordSetProcessor JID-0799ece0581ac5fb2b16c299 INFO: done: 31.488 sec
2017-01-03T12:33:24.171179+00:00 app[worker.1]: [Photo] Processing records with createdAt anchor date: 2016-01-25T12:10:35.356Z...
```

**Comment by rusmichal** [comment]
Hey problem was with my FileKey. I haven't added keyfile and I got 403. I added fileKey to prase-server configuration file and it works.

**Comment by rusmichal** [comment]
How to re-run app?

**Comment by apersaud** [comment]
Glad to hear you figured it out. Let me know what I could add to the documentation to make it more clear.

To re-run the app you can do one of two things. You can run the start task again:

```bash
     $ heroku run rake start -a NAME_OF_YOUR_HEROKU_APP
```

or you can go to the Heroku console, under settings and set `AUTO_START_ON_BOOT` environment variable to `true`. If it is already true, then just restart the dynos, which should kick off the job again.
