### ISSUE TITLE
NameError on Heroku Deploy

### ISSUE THREAD

**Issue by rthomps7** [modernistik/parse-file-migration#2]
I'm not sure what I'm doing wrong here. Can't get Heroku Deploy to work. I'm not a ruby guy, so any help would be appreciated.

```
rake aborted!
NameError: wrong constant name _Product
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:51:in `const_set'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:51:in `rescue in build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:46:in `build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:17:in `block in auto_generate_models!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:16:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:16:in `auto_generate_models!'
/app/config/boot.rb:60:in `<top (required)>'
```

**Comment by rthomps7** [comment]
I might as well drop the whole log:

```
rake aborted!
NameError: wrong constant name _Product
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:51:in `const_set'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:51:in `rescue in build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:46:in `build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:17:in `block in auto_generate_models!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:16:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:16:in `auto_generate_models!'
/app/config/boot.rb:60:in `<top (required)>'
/app/Rakefile:6:in `require'
/app/Rakefile:6:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/bundle:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/bundle:23:in `<main>'
NameError: uninitialized constant Product
Did you mean?  Proc
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:48:in `build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:17:in `block in auto_generate_models!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:16:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.4/lib/parse/model/core/builder.rb:16:in `auto_generate_models!'
/app/config/boot.rb:60:in `<top (required)>'
/app/Rakefile:6:in `require'
/app/Rakefile:6:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/bundle:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => start => environment
```

**Comment by apersaud** [comment]
No worries, I'll look into it. Sometimes with Parse Server, some of the API call flows have changed including the 'Product' table.

**Comment by apersaud** [comment]
I updated the parse-stack gem on the master branch and ran tests and seemed to work fine for those who have a Product table. Can you try it again?

**Comment by rthomps7** [comment]
Great - thanks! We got past that, but now I'm seeing some other errors. Maybe I didn't deploy the updates correctly?

See below:

```
rake aborted!
ArgumentError: Property Parse::User#growl_message_view_displayed_count already defined with data type integer
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/properties.rb:131:in `property'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/builder.rb:67:in `block in build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/builder.rb:56:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/builder.rb:56:in `build!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/builder.rb:17:in `block in auto_generate_models!'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/builder.rb:16:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/parse-stack-1.6.7/lib/parse/model/core/builder.rb:16:in `auto_generate_models!'
/app/config/boot.rb:60:in `<top (required)>'
/app/Rakefile:6:in `require'
/app/Rakefile:6:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/bundle:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => start => environment
```

**Comment by apersaud** [comment]
This looks like a property being automatically defined twice (probably one of yours). A column name of growlMessageViewDisplayCount? Are there multiple columns with similar name?

**Comment by rthomps7** [comment]
Oh yes - sorry. I'm actually just trying to migrate things from an old setup I don't know well, so I missed that. Looks like we have a `growlMessageViewDisplayedCount` and a `GrowlMessageViewDisplayedCount` ... I'm assuming it's case sensitive. 

I removed the one column because it wasn't unused. I am not getting many S3 errors, but I assume that's something wrong with my s3 configuration. I'll keep looking.

Thanks for the help.

**Comment by apersaud** [comment]
Yeah. Just to clarify, we assume column names to be unique and parse-stack expects a convention of lower-first camel case as a column - so `growlMessageViewDisplayedCount` and `GrowlMessageViewDisplayedCount` will technically be mapped to the same property without running your own set up. There is a way to turn off this feature mapping manually, but not using the Heroku button.

Glad it's working out. Will close the issue.
